#include "stdinc.h"
#include "DCPlusPlus.h"
#include "ResourceManager.h"
string ResourceManager::strings[] = {
"Accepted Disconnects", 
"Accepted Timeouts", 
"Active", 
"Enabled / Search String", 
"&Add", 
"Add as source", 
"Add finished files to share instantly (if shared)", 
"Add To Favorites", 
"Added", 
"Automatic Directory Listing Search", 
"Destination Directory", 
"Discard", 
"Download Matches", 
"Enabled", 
"Full Path", 
"ADLSearch Properties", 
"Search String", 
"Max FileSize", 
"Min FileSize", 
"Search Type", 
"Size Type", 
"All", 
"All 3 users offline", 
"All 4 users offline", 
"All download slots taken", 
"All file slots taken", 
"All %d users offline", 
"Searching TTH alternates for: ", 
"-- WARNING --\r\n-- You are in active mode, but have activated passive search. --\r\n-- Don't use passive search if you have search results without this option --\r\n-- because you don't get search result from passive clients !!! --\r\n-- Turn it off in settings => FlylinkDC++ => Always use Passive Mode for Search --\r\n", 
"Any", 
"Autoscroll chat", 
"At least", 
"At most", 
"Audio", 
"Auto", 
"Auto connect / Name", 
"Auto grant slot / Nick", 
"Automatic", 
"Average/s: ", 
"Upload Speed", 
"AWAY", 
"Away mode off", 
"Away mode on: ", 
"Transfer limiter disabled", 
"Transfer limiter enabled", 
"Limit transfer speeds", 
"B", 
"Balloon popups", 
"Bitzi Lookup", 
"Segment Block Finished, waiting...", 
"Both users offline", 
"Browse...", 
"&Browse...", 
"Browse file list", 
"Bumped", 
"Cancel", 
"Certificate not trusted, unable to connect", 
"TLS disabled, failed to generate certificate: ", 
"CID", 
"Clear chat", 
"Client", 
"Close", 
"Close connection", 
"Collapse All", 
"User with fireball", 
"User is OP", 
"Passive user", 
"User with server", 
"Maximum command length exceeded", 
"Compressed", 
"Error during compression", 
"&Configure", 
"Configured Public Hub Lists", 
"&Connect", 
"Connect to all users", 
"Connect to hub", 
"Connected", 
"Connecting...", 
"Connecting (forced)...", 
"Connecting to ", 
"Connecting to server", 
"Connection", 
"Connection closed", 
"Connection error", 
"Connection timeout", 
"Continue Search", 
"Copy", 
"Copy All", 
"Copy description", 
"Copy email address", 
"Copy Exact Share", 
"Copy address to clipboard", 
"Copy IP", 
"Copy actual line", 
"Copy magnet link to clipboard", 
"Copy nick", 
"Copy Nick+IP", 
"Copy TAG", 
"Copy URL", 
"Corruption detected at position", 
"Could not open target file: ", 
"Count", 
"Country", 
"TTH Checked", 
"Hashing", 
"Current version", 
"Data retrieved", 
"Error during decompression", 
"Default", 
"Description", 
"Destination", 
"Directory", 
"Directory or directory name already exists", 
"Disable sounds", 
"Disabled", 
"Disconnect all users", 
"Disconnect user(s)", 
"Disconnected", 
"Disconnected user leaving the hub: ", 
"Document", 
"Done", 
"Don't begin new segment if overall file speed is over", 
"Don't remove /password before your password", 
"The temporary download directory cannot be shared", 
"Download", 
"Download failed: ", 
"Download finished, idle...", 
"Download queue", 
"Download starting...", 
"Download to...", 
"Download whole directory", 
"Download whole directory to...", 
"Download with priority...", 
"Downloaded", 
"Downloaded %s (%.01f%%) in %s", 
" downloaded from ", 
"Downloaded parts", 
"Downloading...", 
"Downloading public hub list...", 
"Downloading list...", 
"Down/Up:", 
"Duplicate source", 
"EB", 
"&Edit", 
"E-Mail", 
"E-Mail", 
"Enable multi-source", 
"Please enter a nickname in the settings dialog!", 
"Please enter a password", 
"Enter search string", 
"Error creating hash data file: ", 
"Error creating adc registry key", 
"Error creating dchub registry key", 
"Error creating magnet registry key", 
"Error hashing ", 
"Error saving hash data: ", 
"Errors", 
"Exact Share", 
"Exact size", 
"Executable", 
"Expand All", 
"Expand search results", 
"Slot ratio", 
"Extra slots set", 
"Failed to shutdown!", 
"Failed to load certificate file", 
"Failed to load private key", 
"Join/part of favorite users showing off", 
"Join/part of favorite users showing on", 
"Favorite name", 
"Under what name you see the directory", 
"Favorite hub added", 
"Hub already exists as a favorite", 
"This hub is not a favorite hub", 
"Identification (leave blank for defaults)", 
"Favorite Hub Properties", 
"Favorite hub removed", 
"Favorite Hubs", 
"Favorite user added", 
"Favorite Users", 
"Favorite user online", 
"File", 
"Subtract list", 
"File list refresh failed: ", 
"File list refresh finished", 
"File list refresh in progress, please wait for it to finish before trying to refresh again", 
"File list refresh initiated", 
"File not available", 
"File type", 
"A file with a different size already exists in the queue", 
"A file with diffent tth root already exists in the queue", 
"Filename", 
"Files", 
"files left", 
"files/h", 
"F&ilter", 
"Filtered", 
"Find", 
"Download finished: %s", 
"Finished Downloads", 
"Upload finished: %s To: %s", 
"Finished Uploads", 
"Folder", 
"Forbidden", 
"File with '$' cannot be downloaded and will not be shared: ", 
"Force attempt", 
"Send garbage on incomming connection (to avoid ISP P2P throttling)", 
"Send garbage on outgoing connection (to avoid ISP P2P throttling)", 
"GB", 
"Get file list", 
"Get user response", 
"Go to directory", 
"Grant extra slot (10 min)", 
"Grant extra slot (day)", 
"Grant extra slot (hour)", 
"Grant extra slot (week)", 
"Extra Slots", 
"Group search results by TTH", 
"Hash database", 
"Creating file index...", 
"Run in background", 
"Statistics", 
"Please wait while FlylinkDC++ indexes your files (they won't be shared until they've been indexed)...", 
"Unable to read hash data file", 
"Hash database rebuilt", 
"Start hashing: ", 
"Hashing failed: ", 
"Finished hashing: ", 
"Hibernate", 
"High", 
"Highest", 
"History", 
"Hits", 
"Hit Ratio: ", 
"Hits: ", 
"Hub", 
"Address", 
"Hub connected", 
"Hub disconnected", 
"Hublist", 
"Hub list downloaded...", 
"Edit the hublist", 
"Name", 
"Hub / Segments", 
"Hub Topic :", 
"Users", 
"Hubs", 
"Chat double click on user action", 
"Cheating user found", 
"zero bytes real size", 
"Check File List", 
"Shared forbidden file : %s", 
"filelist was inflated %s times", 
"Mismatched share size - ", 
"Check user on join", 
", stated size = %[shareshort], real size = %[realshareformat]", 
"Checking client...", 
"Choose folder", 
"Chunk overlapped by faster user", 
"Ignore TTH searches", 
"Ignore User", 
"Ignored message: ", 
"Hub address cannot be empty.", 
"Invalid file list name", 
"Invalid number of slots", 
"Invalid size", 
"Invalid target file (missing directory, check default download directory setting)", 
"Full tree does not match TTH root", 
"Ip: ", 
"Ip", 
"Items", 
"Join/part showing off", 
"Join/part showing on", 
"Joins: ", 
"kB", 
"kB/s", 
"kB/s (0 = disable)", 
"Kick user(s)", 
"Kick user(s) with filename", 
"A file of equal or larger size already exists at the target location", 
"Hub (last seen on if offline)", 
"Last change: ", 
"Time last seen", 
"Latest version", 
"File was corrupted, redownloading %s...", 
"left", 
"Left color", 
"Application \"%s\" caused an unhandled exception in FlylinkDC++. Please uninstall it, upgrade it or use an alternate product.", 
"Upload Limit", 
"Listening socket failed (you need to restart FlylinkDC++): ", 
"Error resolving ", 
"File list loaded.", 
"Loading FlylinkDC++, please wait...", 
"Loading file list, this may take a while if the list is large.", 
"Lock", 
"Log off", 
"Low", 
"Lowest", 
"Filename:", 
"File Hash:", 
"Do nothing", 
"Add this file to your download queue", 
"Do the same action next time without asking", 
"Start a search for this file", 
"File Size:", 
"A MAGNET link was given to FlylinkDC++, but it didn't contain a valid file hash for use on the Direct Connect network.  No action will be taken.", 
"FlylinkDC++ has detected a MAGNET link with a file hash that can be searched for on the Direct Connect network.  What would you like to do?", 
"MAGNET Link detected", 
"Download files from the Direct Connect network", 
"FlylinkDC++", 
"URL:MAGNET URI", 
"Match queue", 
"Matched %d file(s)", 
"Max Hubs", 
"Max number of segments", 
"Max Size", 
"Max Users", 
"Max hubs", 
"Max users", 
"MB", 
"MBits/s", 
"MB/s", 
"About", 
"ADL Search", 
"Arrange icons", 
"Cascade", 
"CDM Debug Messages", 
"Close all file list windows", 
"Close all offline PM windows\tAlt+P", 
"Close all PM windows", 
"Close all search windows", 
"Close disconnected\tAlt+D", 
"Reconnect disconnected\tCtrl+Alt+R", 
"Close all hubs", 
"Close hubs below threshold users", 
"Close hubs with no users", 
"Forums", 
"Donate", 
"&Download Queue\tCtrl+D", 
"E&xit", 
"Frequently asked questions", 
"&Favorite Hubs\tCtrl+F", 
"Favorite &Users\tCtrl+Shift+F", 
"&File", 
"&Recent Hubs", 
"Follow last redirec&t\tCtrl+T", 
"Indexing progress\tCtrl+H", 
"&Help...\tF1", 
"Links/Affiliates", 
"neXTPeer.net", 
"PeerWeb.org", 
"The Ascendent Network", 
"FlylinkDC++ Guides", 
"User Guide", 
"GeoIP database update", 
"Homepage", 
"Horizontal Tile", 
"Minimize &All", 
"Network Statistics", 
"&Notepad\tCtrl+N", 
"Open downloads directory", 
"Open file list...\tCtrl+L", 
"Match downloaded lists", 
"Open own list\tCtrl+Shift+L", 
"&Public Hubs\tCtrl+P", 
"&Quick Connect ...\tCtrl+Q", 
"&Reconnect\tCtrl+R", 
"Refresh file list\tCtrl+E", 
"Restore All", 
"&Search\tCtrl+S", 
"Search spy\tCtrl+Shift+S", 
"Settings...\tCtrl+O", 
"Show FlylinkDC++", 
"&Status bar\tCtrl+2", 
"&Toolbar\tCtrl+1", 
"T&ransfers\tCtrl+3", 
"&Transfers", 
"Get TTH for file...", 
"Vertical Tile", 
"&View", 
"Chat", 
"&Window", 
"Add Files", 
"Options", 
"Display Baloon Popups", 
"Menu bar", 
"Min Share", 
"Min Slots", 
"Minimum search interval", 
"Min share", 
"Min slots", 
"Minutes", 
"Mode", 
"Move/Rename", 
"Move &Down", 
"Move &Up", 
"My nick in mainchat", 
"NetLimiter was detected in your computer. It is frequently responsible for FlylinkDC++ crash, upload disconnecting and slow download speed. Please uninstall it and use an alternate product, or built-in limiter.", 
"Network Statistics", 
"&New...", 
"Remove user from queue, if speed is below", 
"Next", 
"Nick", 
"Your nick was already taken, please change to something else!", 
" (Nick unknown)", 
"No", 
"TLS disabled, no certificate file set", 
"No directory specified", 
"Can't download from passive users when you're passive", 
"You're trying to download from yourself!", 
"No errors", 
"No free block", 
"Hub log not exist", 
"User log not exist", 
"No matches", 
"No needed part", 
"No slots available", 
"No users", 
"No users to download from", 
"Normal", 
"Not listening for connections - please restart DC++", 
"Notepad", 
"segment(s)", 
"Offline", 
"OK", 
"Online", 
"Only users with free slots", 
"Only results with TTH root", 
"Only where I'm op", 
"Open", 
"Open download page?", 
"Open folder", 
"Open hub log", 
"Open user log", 
"Parts: ", 
"Passive user", 
"Password", 
"Path", 
"Local path", 
"Pause Search", 
"Paused", 
"PB", 
"Picture", 
"PK String", 
"Play", 
"Show popup on download failed", 
"Show popup on download finished", 
"Show popup on download begins", 
"Show popup on favorite user connected", 
"Show popup on hub connected", 
"Show popup on hub disconnected", 
"Show popup on cheating user found", 
"Show popup on new private message", 
"Show popup on private message", 
"Popup type", 
"Show popup on upload finished", 
"Port: ", 
"Power off", 
"Press the follow redirect button to connect to ", 
"Preview", 
"Previous folders", 
"Priority", 
"Private message", 
"Private message from ", 
"Transfer progressbar - background", 
"Transfer progressbar - decompressed part", 
"Queue progressbar - downloaded chunks", 
"Queue progressbar - running chunks", 
"Transfer progressbar - actual segment", 
"Queue progressbar - verified chunks", 
"Queue progressbar - common blocks", 
"oDC Style", 
"Stealthy Style", 
"&Properties", 
"Public Hubs", 
"Purge", 
"Enable queue updating in real time (uses more CPU on large queue!)", 
"Quick Connect", 
"Rating", 
"Ratio", 
"Readd source", 
"Really exit?", 
"Really remove?", 
"Reason", 
"Reboot", 
"Recent Hubs", 
"Redirect request received to a hub that's already connected", 
"Redirect user(s)", 
"&Refresh", 
"Refresh user list", 
"Reliability", 
"&Remove", 
"Remove all", 
"Remove extra slot", 
"Remove user from queue", 
"Remove offline users", 
"Remove source", 
" renamed to ", 
"Report user", 
"Report auto search for alternates in status bar", 
"Retrieving data", 
"Right color", 
"Rollback inconsistency, existing file does not match the one being downloaded", 
"Running...", 
"Search", 
"Search for", 
"Search for alternates", 
"Search for file", 
"Filter", 
"Search options", 
"Search spam detected from ", 
"Search Spy", 
"Search String", 
"Searching for ", 
"Seconds", 
"Request to seek beyond the end of data", 
"Segment", 
"Segments", 
"Select all", 
"Select user in list", 
"Send private message", 
"Send public message", 
"Separator", 
"Server", 
"Set priority", 
"Use Alternate Limiting from", 
"Back color", 
"Black & white", 
"Bold Authors of messages in chat", 
"Remove diacritic marks from Czech chars", 
"Default styles", 
"Enable slow downloads disconnecting", 
"Download Speed", 
"Limit transfer speeds", 
"Error color", 
"And whole file speed exceeds", 
"Disconnect download if speed is below", 
"Install Magnet URI handler on startup", 
"And file size is more than", 
"* If upload limit is set, download limit is max 7 x upload limit !!!", 
"* Small Uploads Slots => Slots for filelist and Small Files.", 
"* Minimal upload limit is set to 5x(slots + 1) !!!", 
"Always use passive mode for Search (Use only if you know what this doing !!!)", 
"Lines from log on new PM", 
"Preview", 
"Private message sound", 
"Progressbar colors", 
"Transferview progressbars", 
"Progressbar text colors", 
"Remove Forbidden (Unfinished Kazaa, Win MX, GetRight, eMule, FlylinkDC++)", 
"Secondary transfer limiter", 
"Disconnecting slow downloads", 
"Small file size", 
"Small Upload Slots", 
"Available styles", 
"Text color", 
"Text style", 
"More than", 
"to", 
"Limit transfer speeds", 
"Upload", 
"Upload Speed", 
"Media toolbar and spam settings", 
"Settings", 
"&Add folder", 
"Break on first ADLSearch match", 
"Advanced", 
"Advanced resume using TTH", 
"Show share-checked users", 
"Suppress main chat", 
"Experts only", 
"Allow TLS connections to clients without trusted certificate", 
"Allow TLS connections to hubs without trusted certificate", 
"Use antifragmentation method for downloads", 
"Appearance", 
"Arguments", 
"Auto-away on minimize (and back on restore)", 
"When segmented downloading only (more than 2 active sources)", 
"Automatically follow redirects", 
"Automatically disconnect users who leave the hub", 
"Don't automatically disconnect favorite users who leave the hub", 
"Auto-open at startup", 
"Use Auto Priority by default", 
"Auto refresh time", 
"m", 
"Automatically search for alternative TTH source every", 
"Automatically match queue for auto search hits", 
"No autosearch if sources more", 
"File Preview", 
"Detect conflicting software", 
"Bind address", 
"Tab bolding on content change", 
"Connection type (old DC++ method)", 
"Default (new DC++ method)", 
"Security", 
"Clear search box after each search", 
"Clients", 
"Search Alternate", 
"Bad client", 
"Bad filelist/fakeshare", 
"Client checked", 
"Favorite", 
"File list checked", 
"Full checked", 
"Ignored", 
"Normal", 
"Has reserved slot", 
"Other colors", 
"Command", 
"Enable safe and compressed transfers", 
"Configure Public Hub Lists", 
"Confirm dialog options", 
"Confirm application exit", 
"Confirm favorite hub removal", 
"Confirm item removal in download queue", 
"FlylinkDC++", 
"Highest Priority Extra Download Slots", 
"Debug commands", 
"Default away message", 
"Direct connection", 
"Directories", 
"Display cheats in main chat", 
"Don't announce new FlylinkDC++ versions (version.xml is still downloaded)", 
"Don't download files already in share", 
"Dwnld attempts/second", 
"Default download directory", 
"Limits", 
"Downloads", 
"Select directories to download new files", 
"Maximum simultaneous downloads (0 = infinite)", 
"No new downloads if speed exceeds (kB/s, 0 = disable)", 
"Automatically expand folders in Queue", 
"Extensions", 
"External / WAN IP", 
"Fake detector", 
"Only show joins / parts for favorite users", 
"Favorite download directories", 
"Favorites", 
"Filename", 
"Maximum simultaneous files (0 = infinite)", 
"Filter kick and NMDC debug messages", 
"Activate search/userlist filter by pressing Enter", 
"Firewall with manual port forwarding", 
"Firewall (passive, worst case)", 
"Firewall with UPnP (WinXP+ only)", 
"Format", 
"General", 
"Get User Country", 
"Accept custom user commands from hub", 
"&Change", 
"Ignore private messages from the hub", 
"Ignore private messages from bots", 
"Incoming connection settings (see Help/FAQ if unsure)", 
"Don't delete file lists when exiting", 
"Language file", 
"Limits", 
"Log directory", 
"Log downloads", 
"Log filelist transfers", 
"Log main chat", 
"Log private chat", 
"Log status messages", 
"Log system messages", 
"Log uploads", 
"Log webserver", 
"Logging", 
"Logs", 
"Max compression level", 
"Max hash speed", 
"Max tab rows", 
"Minimize at program startup", 
"Minimize to tray", 
"Mouse Over", 
"Name", 
"Connection settings", 
"Don't send the away message to bots", 
"Nominal bandwidth", 
"Normal", 
"timeout", 
"Note; Files appear in the share only after they've been hashed!", 
"Open new window when using /join", 
"Progressbar colors", 
"Options", 
"Outgoing connection settings", 
"Don't allow hub/UPnP to override", 
"Personal Information", 
"Make an annoying sound every time a private message is received", 
"Make an annoying sound when a private message window is opened", 
"PM history", 
"Open new file list windows in the background", 
"Open new private message windows in the background", 
"Open private messages from the hub in their own window", 
"Open private messages from bots in their own window", 
"Open private messages in their own window", 
"Ports", 
"Autoprio settings - Auto priority option must be OFF!", 
"High prio max size", 
"Highest prio max size", 
"Low prio max size", 
"Set lowest prio for newly added files larger than Low prio size", 
"Normal prio max size", 
"Popup box to input password for hubs", 
"Public Hubs list", 
"HTTP Proxy (for hublist only)", 
"Public Hubs list URL", 
"Queue", 
"Rename", 
"Note; most of these options require that you restart FlylinkDC++", 
"Reset", 
"Rollback", 
"Max sources for match queue", 
"Search history", 
"Segment Downloading", 
"Select color", 
"&Text style", 
"&Window color", 
"Send unknown /commands to the hub", 
"Share hidden files", 
"Total size:", 
"Shared directories", 
"Show InfoTips in lists", 
"Show joins / parts in chat by default", 
"Show progress bars for transfers (uses some CPU)", 
"Show shell menu in finished transfers", 
"Skip zero-byte files", 
"SOCKS5", 
"Socks IP", 
"Port", 
"Use SOCKS5 server to resolve host names", 
"Login", 
"Sort favorite users first", 
"Sounds", 
"Sounds", 
"Note; because of changing download speeds, this is not 100% accurate...", 
"View status messages in main chat", 
"TCP", 
"TLS", 
"Colors & Fonts", 
"Show timestamps in chat by default", 
"Set timestamps", 
"Toggle window when selecting an active tab", 
"Toolbar", 
"Add -->", 
"Toolbar images", 
"<-- Remove", 
"UDP Port", 
"Unfinished downloads directory", 
"Line speed (upload)", 
"Sharing", 
"Folders to share", 
"Automatically open an extra slot if speed is below (0 = disable)", 
"Upload slots", 
"Install URL handler on startup (to handle dchub:// links)", 
"Use CTRL for line history", 
"Use file extension for Download to in search", 
"Use old sharing user interface", 
"Use system icons when browsing files (slows browsing down a bit)", 
"Use TLS when remote client supports it", 
"Use vertical view by default", 
"User List Colors", 
"User Commands", 
"User Menu Items", 
"Enable Webserver", 
"Windows", 
"Window options", 
"Write buffer size", 
"Override system colors", 
"Override system colors", 
"Shared", 
"Shared Files", 
"Display popup in away mode only", 
"Display popup when minimized only", 
"Show speed", 
"Show limiter", 
"Show slots", 
"Description customization", 
"Shutdown computer", 
"Shutdown action", 
"Shutdown sequence deactivated...", 
"Shutdown sequence activated...", 
"Size", 
"Exactly", 
"Min Size", 
"New virtual name matches old name, skipping...", 
"Slot granted", 
"Slots", 
"Slots set", 
"Slow user", 
"Small file size set", 
"Socks server authentication failed (bad login / password?)", 
"The socks server doesn't support login / password authentication", 
"The socks server failed establish a connection", 
"The socks server requires authentication", 
"Failed to set up the socks server for UDP relay (check socks address and port)", 
"Download begins", 
"Download finished", 
"Unhandled Exception", 
"Faker found", 
"Alternate source added", 
"File is corrupted", 
"Typing notification", 
"Upload finished", 
"Remote client does not fully support TTH - cannot download", 
"Source Type", 
"Specify a search string", 
"Specify a server to connect to", 
"Speed", 
"Status", 
"Stored password sent...", 
"String not found: ", 
"Supports", 
"Suspend", 
"Tabs on top", 
"Tag", 
"Target filename too long", 
"TB", 
"Unable to open TCP/TLS port. File transfers will not work correctly until you change settings or turn off any application that might be using the TCP/TLS port", 
"Percent fake share accepted", 
"Manual settings of number of segments", 
"Time", 
"Time left", 
"\r\n- %a - Abbreviated weekday name\r\n- %A - Full weekday name\r\n- %b - Abbreviated month name\r\n- %B - Full month name\r\n- %c - Date and time representation appropriate for locale\r\n- %d - Day of month as decimal number (01 – 31)\r\n- %H - Hour in 24-hour format (00 – 23)\r\n- %I - Hour in 12-hour format (01 – 12)\r\n- %j - Day of year as decimal number (001 – 366)\r\n- %m - Month as decimal number (01 – 12)\r\n- %M - Minute as decimal number (00 – 59)\r\n- %p - Current locale's A.M./P.M. indicator for 12-hour clock\r\n- %S - Second as decimal number (00 – 59)\r\n- %U - Week of year as decimal number, with Sunday as first day of week (00 – 53)\r\n- %w - Weekday as decimal number (0 – 6; Sunday is 0)\r\n- %W - Week of year as decimal number, with Monday as first day of week (00 – 53)\r\n- %x - Date representation for current locale\r\n- %X - Time representation for current locale\r\n- %y - Year without century, as decimal number (00 – 99)\r\n- %Y - Year with century, as decimal number\r\n- %z, %Z - Either the time-zone name or time zone abbreviation, depending on registry settings; no characters if time zone is unknown\r\n- %% - Percent sign\r\n\r\nDefault: %H:%M:%S", 
"Timestamps Help", 
"Timestamps disabled", 
"Timestamps enabled", 
"More data was sent than was expected", 
"Total: ", 
"Transferlist double click action", 
"Transferred", 
"A file with the same hash already exists in your share", 
"TTH Inconsistency", 
"TTH Root", 
"Two colors", 
"Type", 
"Unable to create thread", 
"Unable to open filelist: ", 
"Unable to rename ", 
"Unable to send file ", 
"Unignore User", 
"Unknown", 
"Unknown command: ", 
"Unknown error: 0x%x", 
"Update check", 
"Upload finished, idle...", 
"Upload starting...", 
"Uploaded %s (%.01f%%) in %s", 
" uploaded to ", 
"Failed to create port mappings. Please set up your NAT yourself.", 
"Failed to get external IP via  UPnP. Please set it yourself.", 
"Failed to remove port mappings", 
"User", 
"Command", 
"Context", 
"Filelist Menu", 
"Hub IP / DNS (empty = all, 'op' = where operator)", 
"Hub Menu", 
"Chat", 
"Send once per nick", 
"Parameters", 
"PM", 
"Text sent to hub", 
"Raw", 
"Search Menu", 
"To", 
"Command Type", 
"User Menu", 
"Create / Modify Command", 
"User Description", 
"User offline", 
"Running... (user online)", 
"User went offline", 
"User went online", 
"Info User", 
"Userlist Icons", 
"Userlist double click action", 
"Chat userlist double click action", 
"Users", 
"Running... (%d of %d users online)", 
"Version", 
"Video", 
"View as text", 
"Virtual name", 
"Virtual directory name already exists", 
"Name under which the others see the directory", 
"Waiting...", 
"Waiting for %i seconds before searching...", 
"Waiting for connection...", 
"Waiting time", 
"Waiting to retry...", 
"Waiting (User online)", 
"Waiting Users", 
"Waiting (%d of %d users online)", 
"Webserver", 
"What's &this?", 
"Whois ", 
"/winamp - Works with Winamp 1.x, 2.x, 5.x (no Winamp 3 support)\r\n- %[version]	Numerical Version (ex: 2.91)\r\n- %[state]	Playing state (ex: stopped/paused/playing)\r\n- %[title]		Window title from Winamp - if you want to change this for mp3s, Winamp > Pref > Input > MPEG > Title\r\n- %[rawtitle]	Window title from Winamp (if %[title] not working propertly)\r\n- %[percent]	Percentage (ex. 40%)\r\n- %[length]	Length in minutes:seconds (ex: 04:09)\r\n- %[elapsed]	Time elapsed in minutes:seconds (ex. 03:51)\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[bitrate]	Bitrate (ex. 128kbps)\r\n- %[sample]	Sample frequency (ex. 22kHz)\r\n- %[channels]	Number of channels (ex. stereo / mono)\r\n\r\nEmpty = Default String -> +me playing: %[title] at %[bitrate] <Winamp %[version]>\r\n\r\nNote about The KMPlayer:\r\nYou can use most of the features offered by /winamp command and all features of the media toolbar also with The KMPlayer.\r\nParameters that are known not to work (or return incorrect values) are %[version], %[bitrate], %[sample] and %[channels].\r\nIt's also very likely that you will need to use %[rawtitle] instead of %[title] to get the correct output.", 
"Winamp Help", 
"Yes", 
"ZoneAlarm was detected in your computer.  It is frequently responsible for corrupted downloads and is the cause of many \"rollback inconsistency\" errors.  Please uninstall it and use an alternate product.  ", 
"Hide hub topics", 
"Enter password", 
"Password required", 
"Share skiplist (wildcard: *, separator: ;)", 
"Check connection", 
"Back", 
"Play", 
"Pause", 
"Next", 
"Stop", 
"Volume up", 
"Volume 50% / Mute", 
"Volume down", 
"Media Toolbar\tCtrl+4", 
"Post media spam to main chat", 
"Threshold users", 
"PeerGuardian Plugin", 
"Get IP address", 
"Update IP on startup", 
"Show preview of private message on popup", 
"Priority based on filename", 
"Highest:", 
"Lowest:", 
"Popup time", 
"Misc", 
"Secondary away message", 
"5 ticks down speed:", 
"5 ticks up speed:", 
"Delay when sending $PSR (in seconds)", 
"Attempt to show users IP in chat", 
"Attempt to show users country in chat", 
"Noon", 
"Midnight", 
" AM", 
" PM", 
"Start hubs minimized", 
"Save settings window state", 
"Enable $HubTopic support", 
"Mainchat buffer size, max size ~2.1 billion (2^31)", 
"Hide share in this hub (OP's only)", 
"Show joins", 
"Emulate DC++ in this hub", 
"User is already in the list of ignored users!", 
"Ignored users", 
"Clear", 
"Format bold, italics and underline in chat (may cause some display problems with MOTD's and ASCII pictures)", 
"Protected prefixes", 
"Exclude users from client checking (use ; as separator and * as wildcard)", 
"/wmp - Works with Windows Media Player 9+\r\n- %[version]	Version of Windows Media Player\r\n- %[fullversion]	Full version of Windows Media Player\r\n- %[status]	Pre-formatted status string from Windows Media Player\r\n- %[title]		Name of the currently playing item\r\n- %[elapsed]	Time elapsed in (HH:)MM:SS\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Full length of the current item in (HH:)MM:SS\r\n- %[artist]	Name of the artist for the currently playing item\r\n- %[album]	Name of the album the current song is from\r\n- %[genre]	Genre of the current media\r\n- %[bitrate]	Bitrate for the playing media\r\n- %[year]	Year of album publiciation (no WMP9 support)\r\n- %[size]		Size of the currently playing file\r\n- %[rating]	Users rating, represented with *'s (if available)\r\n\r\nEmpty = Default String -> +me %[title] at %[bitrate] <Windows Media Player %[version]>", 
"Windows Media Player Help", 
"/itunes - For iTunes media spamming\r\n- %[version]	Numerical Version (ex: 7.0.2.16)\r\n- %[album]	Name of the album the current track is from\r\n- %[artist]	Artist of the current track\r\n- %[title]		Name of the currently playing track\r\n- %[genre]	Genre of the currently playing track\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current track\r\n- %[bitrate]	Bitrate for the playing track (kbps)\r\n- %[frequency]	Frequency for the currently playing track (kHz)\r\n- %[year]	Year of publiciation/recording of the current track\r\n- %[size]		Size of the currently playing file\r\n- %[state]	Current state of iTunes (playing/stopped)\r\n\r\nEmpty = Default String -> +me playing: %[title] at %[bitrate] <iTunes %[version]>", 
"iTunes Help", 
"/mpc - For Media Player Classic media spamming\r\n- %[filename]	Name of the file currently playing\r\n- %[title]		Name of the cyrrently playing item (without file extension)\r\n- %[size]		Size of the file currently playing\r\n- %[state]	Current state of Media Player Classic (playing/paused/stopped)\r\n- %[elapsed]	Time elapsed in minutes:seconds\r\n- %[percent]	Time elapsed presented as percentage from total length\r\n- %[bar]		ASCII progress bar, 10 characters wide no including brackets (ex. [----|-----])\r\n- %[length]	Total length of the current file\r\n\r\nEmpty = Default String -> +me playing: %[title] <Media Player Classic>", 
"Media Player Classic Help", 
"Selected player doesn't support media spams", 
"Auto protect favourite users", 
"Raw texts (don't enter your raw commands here)", 
"Can bypass limiter", 
"OP Chat names (wildcards supported)", 
"Blocked by PeerGuardian Plugin", 
"Exclude hub from automatic client/fake checking", 
"&Back color", 
"&Msg text", 
"&Title text", 
"Max length", 
"Popup image", 
"FlylinkDC++ has crashed...", 
"The following application error has occurred:", 
"If this problem persists, copy the above exception information to the clipboard, and send it to FlylinkDC++ forums.", 
"Reconnect after termination of the application", 
"Copy Exception", 
"Continue", 
"Terminate Application", 
"Open log files internally (performance may decrase when opening huge log files)", 
"Don't show emoticons in messages with links", 
"!SMT!-S", 
"Ignore private messages", 
"Upload Speed Limit", 
"Send to All Users", 
"Ban if open slot less than", 
"Ban if shared less than, Gb", 
"Ban upl speed limit less, Kb", 
"Message on ban", 
"Repeat PM period (0 - disable PM), min", 
"Stealth ban", 
"Send PM, even if client supports BanMsg in transfers list", 
"Don't ban OPs", 
"Extra-slot to users i'm downloading from", 
"Client ID and version", 
"!SMT!-P", 
"GiveExtraSlot", 
"HighPriotity", 
"NormalPriotity", 
"LowPriotity", 
"!SMT!-IP", 
"DNS", 
"Location", 
"!SMT!-UI", 
"Summary user report", 
"User waiting files", 
"Queued downloads from user", 
"Save as...", 
"Ban Color", 
"Dupe Color", 
"ApexDC-mod Colors", 
"Show popup on favorite user offline", 
"Favorite user offline", 
"Multiline input field in chat window", 
"Preview text files in external program", 
"Extra-slot timeout", 
"Enter period (HH:MM or DD:HH:MM)", 
"Invalid time format", 
"grants you an extra-slot for", 
"removed your extra-slot", 
"Send PMs on grant/remove slot", 
"Ask slot", 
"hello %[nick]. plz gimme slot for %[filename]", 
"Favorite user list double click action", 
"!SMT!-PSW", 
"Messages", 
"Protect private area with password", 
"Password", 
"Password hint", 
"pokemon", 
"user has been disabled receiving PMs. use password *pokemon* in case of emergency. dont abuse: slot-askers will be banned+ignored forever and will not download even in queue order", 
"Free PM access", 
"Copy magnet as web link", 
"Set fast upload file", 
"Finished downloads\tCtrl+Shift+D", 
"Waiting users\tCtrl+U", 
"Finished uploads\tCtrl+Shift+U", 
"Upload Transfer Colors", 
"\t\t\t\t\t HELP \t\t\t\t\t\t\t\t", 
"On/Off away mode with specific (message)", 
"Clear chat window", 
"On/Off showing join/part of favorite users", 
"On/Off showing join/part in mainchat", 
"On/Off timestamps", 
"Changes number of slots to #", 
"Changes number of extra slots for small files to #", 
"Changes max \"Small file\" size to # Kb", 
"Refreshes list of shared files", 
"Rebuilds share", 
"Joins hub with address #", 
"Close current window", 
"Add hub to favorites (in PM adds user to friens)", 
"Removes current hub from favorites", 
"Show/hide userlist" , 
"Show ignorelist in chat", 
"Add (user) to favorite", 
"Sends private (message) to (user)", 
"Get (user) filelist" , 
"Shows IP and port where connected", 
"Print FlylinkDC++ version to chat", 
"Shows some statistics about client", 
"Open (url) in default browser" , 
"Save download queue", 
"Do a search of (string)", 
"Activate shutdown sequence", 
"Speak from third person", 
"Print Winamp (WMP, Itunes, MP Classic) info to chat", 
"\t\tFor more help please visit FlylinkDC++ Forums (Help -> Forums)", 
"You are connected to a hub in a passive mode!! We recommend to be switched in an active mode!!", 
"Backup Settings at startup", 
"ADLSearch is a tool for fast searching of directory listings downloaded from users. \nCreate a new ADLSearch entering 'avi' as search string for example. When you \ndownload a directory listing from a user, all avi-files will be placed in a special folder \ncalled <<<ADLSearch>>> for easy finding. It is almost the same as using the standard \n'Find' multiple times in a directory listing. \n\nSpecial options: \n- 'Active' check box selects if the search is used or not. \n- 'Source Type' can be the following options; 'Filename' matches search against filename, \n   'Directory' matches against current subdirectory and places the whole structure in the \n   special folder, 'Full Path' matches against whole directory + filename. \n- 'Destination Directory' selects the special output folder for a search. Multiple folders \n   with different names can exist simultaneously. \n- 'Min/Max Size' sets file size limits. This is not used for 'Directory' type searches. \n- 'Move Up'/'Move Down' can be used to organize the list of searches. \n\nThere is a new option in the context menu (right-click) for directory listings. It is called \n'Go to directory' and can be used to jump to the original location of the file or directory. \n\nExtra features:\n\n1) If you use %y.%m.%d in a search string it will be replaced by todays date. Switch \nplace on y/m/d, or leave any of them out to alter the substitution. If you use %[nick] \nit will be replaced by the nick of the user you download the directory listing from. \n\n2) If you name a destination directory 'discard', it will not be shown in the total result. \nUseful with the extra feature 3) below to remove uninteresting results. \n\n3) There is a switch called 'Break on first ADLSearch match' in Settings->Advanced'.  \nIf enabled, ADLSearch will stop after the first match for a specific file/directory. \nThe order in the ADLSearch windows is therefore important. Example: Add a search \nitem at the top of the list with string='xxx' and destination='discard'. It will catch \nmany pornographic files and they will not be included in any following search results.", 
"ADL Search Brief", 
"IP Filter", 
"IPTrust.ini not found...", 
"File with rules for IP Filter:", 
"Current rules:", 
"IP Filter configured depending on provider", 
"Trust IP address", 
"Use global layout for hub windows (overrides favorite hub specific preferences)", 
"Comment", 
"RegExp", 
"Case sensitive", 
"Invalid RegExp!", 
"RegExp Tester", 
"It's a match!", 
"It's not a match.", 
"Case insensitive RegExp", 
"Match", 
"Don't perform ADLSearches in this hub", 
"Overrides Fav. Hubs", 
"Action", 
"No Action", 
"Forbidden Files", 
"The first entry may be accessed with %[opchat] from raw and user commands but in order for this to work it may not contain any wildcard characters in it.", 
"Profile version", 
"Profile Info", 
"Params", 
"Name or RegExp must not be empty", 
"Check finished files for viruses", 
"Use RegExp and/or wildcards", 
"Indicate speeds (Stealthy Style)", 
"Use traditional tray icon behavior", 
"Use the old way (StrongDC 1.x) of displaying hub names", 
"Already Shared", 
"Flag clients without full TTH support as bad/faking", 
"Disconnect raw", 
"Timeout raw", 
"Fake share raw", 
"ListLen mismatch", 
"Filelist too small", 
"Filelist unavailable", 
"Old client (no full support for TTH)", 
"Set action:", 
"Delete checked filelists", 
"Client checking finished, idle...", 
"Always on top", 
"Lock Toolbars", 
"Use autocomplete in search window (turns on persistent search history)", 
"Keep downloads history between sessions", 
"Keep upload history between sessions", 
"Fake share detector", 
"Raw commands", 
"Log chat", 
"Protected prefixes (wildcards supported, use semicolon to separate entries)", 
"Quick Search\tCtrl+5", 
"Quick Search...", 
"Automatically switch search type to TTH when one is found in search string", 
"Display full info for filelists in download queue", 
"It's no use trying to download from bot", 
"Icons compatibility mode:", 
"Zion++ (> 2.16)", 
"StrongDC++ (1.x)", 
"Use Zion styled tabs (requires restart)", 
"Place all non-hub tabs in front", 
"Use mini tabs for all hubs (if enabled the favourite hub properties option is reversed)", 
"Mini tab", 
"Normal tab", 
"Old password:", 
"New password:", 
"Confirm new:", 
"Blend offline search results", 
"Max resize lines", 
"incoming", 
"outgoing", 
"Begin", 
"End", 
"Auto-open hub's OP Chat", 
"Ratio message template", 
"You can use:\r\n -%[ratio] - up/down ratio\r\n -%[up] - data uploaded\r\n -%[down] - data downloaded", 
"Ratio meaasge template help", 
"Supported version of Winamp is not running", 
"Join FlylinkDC++ Team: ", 
"Help", 
"Use custom list background style", 
"Mainchat buffer size, max size ~2.1 billion (2^31)", 
"Active Transfers", 
"Hide", 
"Show", 
"Users", 
"Filter", 
"TTH", 
"CD-DVD Image", 
"Don't care", 
"Search", 
"Find", 
"Advanced", 
"Basic", 
"Downloads", 
"Uploads", 
"Nick", 
"Contacts", 
"Chat", 
"Queue saved", 
"Public Chat", 
"Private Chat", 
"File Listing", 
"File Download", 
"Directory Download", 
"Download Directory", 
"Download Directory To", 
"Preview", 
"Expert Mode", 
"Network Settings Help", 
"Upload Settings Help", 
"Nick is empty", 
"Search settings", 
"Expand toolbar on search results window activate", 
"Restore search condition on search results window activate", 
"Enable sounds", 
"Settings", 
"Away", 
"User", 
"Status", 
"Download Queue", 
"Upload Queue", 
"Finished Downloads", 
"Finished Uploads", 
"Download Queue", 
"Pause", 
"Start", 
"Delete", 
"Priority:", 
"Add to Favorites", 
"Private Message", 
"Reconnect", 
"Configure", 
"Add Files", 
"Open own File List", 
"Refresh File List", 
"My Provider", 
"Attention!", 
"Select Provider", 
"Magnet link handling preferences", 
"Select action for magnet-link in dialog", 
"Automatically perform", 
"Download", 
"Search", 
"Advices", 
"Subscriptions", 
"Subscriptions", 
"Blocked by IP filter", 
"Open hub chat on connect", 
"Minimize on close", 
"Use custom video player", 
};
string ResourceManager::names[] = {
"AcceptedDisconnects", 
"AcceptedTimeouts", 
"Active", 
"ActiveSearchString", 
"Add", 
"AddAsSource", 
"AddFinishedInstantly", 
"AddToFavorites", 
"Added", 
"AdlSearch", 
"AdlsDestination", 
"AdlsDiscard", 
"AdlsDownload", 
"AdlsEnabled", 
"AdlsFullPath", 
"AdlsProperties", 
"AdlsSearchString", 
"AdlsSizeMax", 
"AdlsSizeMin", 
"AdlsType", 
"AdlsUnits", 
"All", 
"All3UsersOffline", 
"All4UsersOffline", 
"AllDownloadSlotsTaken", 
"AllFileSlotsTaken", 
"AllUsersOffline", 
"AlternatesSend", 
"AntiPassiveSearch", 
"Any", 
"AscrollChat", 
"AtLeast", 
"AtMost", 
"Audio", 
"Auto", 
"AutoConnect", 
"AutoGrant", 
"Automatic", 
"Average", 
"AverageUpload", 
"Away", 
"AwayModeOff", 
"AwayModeOn", 
"LimiterOff", 
"LimiterOn", 
"TrayLimiter", 
"B", 
"BalloonPopups", 
"BitziLookup", 
"BlockFinished", 
"BothUsersOffline", 
"Browse", 
"BrowseAccel", 
"BrowseFileList", 
"Bumped", 
"Cancel", 
"CertificateNotTrusted", 
"CertificateGenerationFailed", 
"Cid", 
"Clear", 
"Clientid", 
"Close", 
"CloseConnection", 
"CollapseAll", 
"ColorFast", 
"ColorOp", 
"ColorPasive", 
"ColorServer", 
"CommandTooLong", 
"Compressed", 
"CompressionError", 
"Configure", 
"ConfiguredHubLists", 
"Connect", 
"ConnectAll", 
"ConnectFavuserHub", 
"Connected", 
"Connecting", 
"ConnectingForced", 
"ConnectingTo", 
"ConnectingToServer", 
"Connection", 
"ConnectionClosed", 
"ConnectionError", 
"ConnectionTimeout", 
"ContinueSearch", 
"Copy", 
"CopyAll", 
"CopyDescription", 
"CopyEmailAddress", 
"CopyExactShare", 
"CopyHub", 
"CopyIp", 
"CopyLine", 
"CopyMagnetLink", 
"CopyNick", 
"CopyNickIp", 
"CopyTag", 
"CopyUrl", 
"CorruptionDetected", 
"CouldNotOpenTargetFile", 
"Count", 
"Country", 
"CrcChecked", 
"CreatingHash", 
"CurrentVersion", 
"DataRetrieved", 
"DecompressionError", 
"Default", 
"Description", 
"Destination", 
"Directory", 
"DirectoryAddError", 
"DisableSounds", 
"Disabled", 
"DisconnectAll", 
"DisconnectUser", 
"Disconnected", 
"DisconnectedUser", 
"Document", 
"Done", 
"DontAddSegmentText", 
"DontRemoveSlashPassword", 
"DontShareTempDirectory", 
"Download", 
"DownloadFailed", 
"DownloadFinishedIdle", 
"DownloadQueue", 
"DownloadStarting", 
"DownloadTo", 
"DownloadWholeDir", 
"DownloadWholeDirTo", 
"DownloadWithPriority", 
"Downloaded", 
"DownloadedBytes", 
"DownloadedFrom", 
"DownloadedParts", 
"Downloading", 
"DownloadingHubList", 
"DownloadingList", 
"Du", 
"DuplicateSource", 
"Eb", 
"EditAccel", 
"Email", 
"SettingsGeneralEmail", 
"EnableMultiSource", 
"EnterNick", 
"EnterPassword", 
"EnterSearchString", 
"ErrorCreatingHashDataFile", 
"ErrorCreatingRegistryKeyAdc", 
"ErrorCreatingRegistryKeyDchub", 
"ErrorCreatingRegistryKeyMagnet", 
"ErrorHashing", 
"ErrorSavingHash", 
"Errors", 
"ExactShared", 
"ExactSize", 
"Executable", 
"ExpandAll", 
"ExpandedResults", 
"ExtraHubSlots", 
"ExtraSlotsSet", 
"FailedToShutdown", 
"FailedToLoadCertificate", 
"FailedToLoadPrivateKey", 
"FavJoinShowingOff", 
"FavJoinShowingOn", 
"FavoriteDirName", 
"FavoriteDirNameLong", 
"FavoriteHubAdded", 
"FavoriteHubAlreadyExists", 
"FavoriteHubDoesNotExist", 
"FavoriteHubIdentity", 
"FavoriteHubProperties", 
"FavoriteHubRemoved", 
"FavoriteHubs", 
"FavoriteUserAdded", 
"FavoriteUsers", 
"FavuserOnline", 
"File", 
"FileListDiff", 
"FileListRefreshFailed", 
"FileListRefreshFinished", 
"FileListRefreshInProgress", 
"FileListRefreshInitiated", 
"FileNotAvailable", 
"FileType", 
"FileWithDifferentSize", 
"FileWithDifferentTth", 
"Filename", 
"Files", 
"FilesLeft", 
"FilesPerHour", 
"Filter", 
"Filtered", 
"Find", 
"FinishedDownload", 
"FinishedDownloads", 
"FinishedUpload", 
"FinishedUploads", 
"Folder", 
"Forbidden", 
"ForbiddenDollarFile", 
"ForceAttempt", 
"GarbageIncoming", 
"GarbageOutgoing", 
"Gb", 
"GetFileList", 
"GetUserResponses", 
"GoToDirectory", 
"GrantExtraSlot", 
"GrantExtraSlotDay", 
"GrantExtraSlotHour", 
"GrantExtraSlotWeek", 
"GrantSlotsMenu", 
"GroupSearchResults", 
"HashDatabase", 
"HashProgress", 
"HashProgressBackground", 
"HashProgressStats", 
"HashProgressText", 
"HashReadFailed", 
"HashRebuilt", 
"HashingStarted", 
"HashingFailed", 
"HashingFinished", 
"Hibernate", 
"High", 
"Highest", 
"History", 
"HitCount", 
"HitRatio", 
"Hits", 
"Hub", 
"HubAddress", 
"HubConnected", 
"HubDisconnected", 
"HubList", 
"HubListDownloaded", 
"HubListEdit", 
"HubName", 
"HubSegments", 
"HubTopic", 
"HubUsers", 
"Hubs", 
"Chatdblclickaction", 
"CheatingUser", 
"Check0byteShare", 
"CheckFilelist", 
"CheckForbidden", 
"CheckInflated", 
"CheckMismatchedShareSize", 
"CheckOnConnect", 
"CheckShowRealShare", 
"CheckingClient", 
"ChooseFolder", 
"ChunkOverlapped", 
"IgnoreTthSearches", 
"IgnoreUser", 
"IgnoredMessage", 
"IncompleteFavHub", 
"InvalidListname", 
"InvalidNumberOfSlots", 
"InvalidSize", 
"InvalidTargetFile", 
"InvalidTree", 
"Ip", 
"IpBare", 
"Items", 
"JoinShowingOff", 
"JoinShowingOn", 
"Joins", 
"Kb", 
"Kbps", 
"KbpsDisable", 
"KickUser", 
"KickUserFile", 
"LargerTargetFileExists", 
"LastHub", 
"LastChange", 
"LastSeen", 
"LatestVersion", 
"LeafCorrupted", 
"Left", 
"LeftColor", 
"LibCrash", 
"Limit", 
"ListenerFailed", 
"HostResolveFailed", 
"LoadedFileList", 
"Loading", 
"LoadingFileList", 
"Lock", 
"LogOff", 
"Low", 
"Lowest", 
"MagnetDlgFile", 
"MagnetDlgHash", 
"MagnetDlgNothing", 
"MagnetDlgQueue", 
"MagnetDlgRemember", 
"MagnetDlgSearch", 
"MagnetDlgSize", 
"MagnetDlgTextBad", 
"MagnetDlgTextGood", 
"MagnetDlgTitle", 
"MagnetHandlerDesc", 
"MagnetHandlerRoot", 
"MagnetShellDesc", 
"MatchQueue", 
"MatchedFiles", 
"MaxHubs", 
"MaxSegmentsNumber", 
"MaxSize", 
"MaxUsers", 
"Maxhubs", 
"Maxusers", 
"Mb", 
"Mbitsps", 
"Mbps", 
"MenuAbout", 
"MenuAdlSearch", 
"MenuArrange", 
"MenuCascade", 
"MenuCdmdebugMessages", 
"MenuCloseAllDirList", 
"MenuCloseAllOfflinePm", 
"MenuCloseAllPm", 
"MenuCloseAllSearchframe", 
"MenuCloseDisconnected", 
"MenuReconnectDisconnected", 
"MenuCloseAllHubs", 
"MenuCloseHubsBelow", 
"MenuCloseHubsEmpty", 
"MenuDiscuss", 
"MenuDonate", 
"MenuDownloadQueue", 
"MenuExit", 
"MenuFaq", 
"MenuFavoriteHubs", 
"MenuFavoriteUsers", 
"MenuFile", 
"MenuFileRecentHubs", 
"MenuFollowRedirect", 
"MenuHashProgress", 
"MenuHelp", 
"MenuSites", 
"MenuSitesNxp", 
"MenuSitesPeerweb", 
"MenuSitesTan", 
"MenuSitesGuides", 
"MenuSitesGuide", 
"MenuHelpGeoipfile", 
"MenuHomepage", 
"MenuHorizontalTile", 
"MenuMinimizeAll", 
"MenuNetworkStatistics", 
"MenuNotepad", 
"MenuOpenDownloadsDir", 
"MenuOpenFileList", 
"MenuOpenMatchAll", 
"MenuOpenOwnList", 
"MenuPublicHubs", 
"MenuQuickConnect", 
"MenuReconnect", 
"MenuRefreshFileList", 
"MenuRestoreAll", 
"MenuSearch", 
"MenuSearchSpy", 
"MenuSettings", 
"MenuShow", 
"MenuStatusBar", 
"MenuToolbar", 
"MenuTransferView", 
"MenuTransfers", 
"MenuTth", 
"MenuVerticalTile", 
"MenuView", 
"MenuViewChat", 
"MenuWindow", 
"MenuFilelistAddFile", 
"MenuOptions", 
"MenuOptionsDisplayBaloonPopups", 
"Menubar", 
"MinShare", 
"MinSlots", 
"MinimumSearchInterval", 
"Minshare", 
"Minslots", 
"Minutes", 
"Mode", 
"Move", 
"MoveDown", 
"MoveUp", 
"MynickInChat", 
"NetlimiterWarning", 
"NetworkStatistics", 
"New", 
"NewDisconnect", 
"Next", 
"Nick", 
"NickTaken", 
"NickUnknown", 
"No", 
"NoCertificateFileSet", 
"NoDirectorySpecified", 
"NoDownloadsFromPassive", 
"NoDownloadsFromSelf", 
"NoErrors", 
"NoFreeBlock", 
"NoLogForHub", 
"NoLogForUser", 
"NoMatches", 
"NoNeededPart", 
"NoSlotsAvailable", 
"NoUsers", 
"NoUsersToDownloadFrom", 
"Normal", 
"NotListening", 
"Notepad", 
"NumberOfSegments", 
"Offline", 
"Ok", 
"Online", 
"OnlyFreeSlots", 
"OnlyTth", 
"OnlyWhereOp", 
"Open", 
"OpenDownloadPage", 
"OpenFolder", 
"OpenHubLog", 
"OpenUserLog", 
"Parts", 
"PassiveUser", 
"Password", 
"Path", 
"LocalPath", 
"PauseSearch", 
"Paused", 
"Pb", 
"Picture", 
"Pk", 
"Play", 
"PopupDownloadFailed", 
"PopupDownloadFinished", 
"PopupDownloadStart", 
"PopupFavoriteConnected", 
"PopupHubConnected", 
"PopupHubDisconnected", 
"PopupCheatingUser", 
"PopupNewPm", 
"PopupPm", 
"PopupType", 
"PopupUploadFinished", 
"Port", 
"PowerOff", 
"PressFollow", 
"PreviewMenu", 
"PreviousFolders", 
"Priority", 
"PrivateMessage", 
"PrivateMessageFrom", 
"ProgressBack", 
"ProgressCompress", 
"ProgressDownloaded", 
"ProgressRunning", 
"ProgressSegment", 
"ProgressVerified", 
"ProgressAvoiding", 
"ProgressbarOdcStyle", 
"ProgressbarStealthyStyle", 
"Properties", 
"PublicHubs", 
"Purge", 
"QueueUpdating", 
"QuickConnect", 
"Rating", 
"Ratio", 
"ReaddSource", 
"ReallyExit", 
"ReallyRemove", 
"Reason", 
"Reboot", 
"RecentHubs", 
"RedirectAlreadyConnected", 
"RedirectUser", 
"Refresh", 
"RefreshUserList", 
"Reliability", 
"Remove", 
"RemoveAll", 
"RemoveExtraSlot", 
"RemoveFromAll", 
"RemoveOffline", 
"RemoveSource", 
"RenamedTo", 
"Report", 
"ReportAlternates", 
"RetrievingData", 
"RightColor", 
"RollbackInconsistency", 
"Running", 
"Search", 
"SearchFor", 
"SearchForAlternates", 
"SearchForFile", 
"SearchInResults", 
"SearchOptions", 
"SearchSpamFrom", 
"SearchSpy", 
"SearchString", 
"SearchingFor", 
"Seconds", 
"SeekBeyondEnd", 
"Segment", 
"Segments", 
"SelectAll", 
"SelectUserList", 
"SendPrivateMessage", 
"SendPublicMessage", 
"Separator", 
"Server", 
"SetPriority", 
"SetczdcAlternateLimiting", 
"SetczdcBackColor", 
"SetczdcBlackWhite", 
"SetczdcBold", 
"SetczdcCzcharsDisable", 
"SetczdcDefaultStyle", 
"SetczdcDisconnectingEnable", 
"SetczdcDownloadSpeed", 
"SetczdcEnableLimiting", 
"SetczdcErrorColor", 
"SetczdcHDownSpeed", 
"SetczdcIDownSpeed", 
"SetczdcMagnetUriHandler", 
"SetczdcMinFileSize", 
"SetczdcNoteDownload", 
"SetczdcNoteSmallUp", 
"SetczdcNoteUpload", 
"SetczdcPassiveSearch", 
"SetczdcPmLines", 
"SetczdcPreview", 
"SetczdcPrivateSound", 
"SetczdcProgressbarColors", 
"SetczdcProgressbarColorsTw", 
"SetczdcProgressbarText", 
"SetczdcRemoveForbidden", 
"SetczdcSecondaryLimiting", 
"SetczdcSlowDisconnect", 
"SetczdcSmallFiles", 
"SetczdcSmallUpSlots", 
"SetczdcStyles", 
"SetczdcTextColor", 
"SetczdcTextStyle", 
"SetczdcTimeDown", 
"SetczdcTo", 
"SetczdcTransferLimiting", 
"SetczdcUpload", 
"SetczdcUploadSpeed", 
"SetczdcWinamp", 
"Settings", 
"SettingsAddFolder", 
"SettingsAdlsBreakOnFirst", 
"SettingsAdvanced", 
"SettingsAdvancedResume", 
"SettingsAdvancedShowShareCheckedUsers", 
"SettingsAdvancedSuppressMainChat", 
"SettingsAdvanced3", 
"SettingsAllowUntrustedClients", 
"SettingsAllowUntrustedHubs", 
"SettingsAntiFrag", 
"SettingsAppearance", 
"SettingsArgument", 
"SettingsAutoAway", 
"SettingsAutoDropSegmentedSource", 
"SettingsAutoFollow", 
"SettingsAutoKick", 
"SettingsAutoKickNoFavs", 
"SettingsAutoOpen", 
"SettingsAutoPriorityDefault", 
"SettingsAutoRefreshTime", 
"SettingsAutoRefreshTimeunit", 
"SettingsAutoSearch", 
"SettingsAutoSearchAutoMatch", 
"SettingsAutoSearchLimit", 
"SettingsAvipreview", 
"SettingsBadSoftware", 
"SettingsBindAddress", 
"SettingsBoldOptions", 
"SettingsBwboth", 
"SettingsBwsingle", 
"SettingsCertificates", 
"SettingsClearSearch", 
"SettingsClients", 
"SettingsColorAlternate", 
"SettingsColorBadClient", 
"SettingsColorBadFilelist", 
"SettingsColorClientChecked", 
"SettingsColorFavorite", 
"SettingsColorFilelistChecked", 
"SettingsColorFullChecked", 
"SettingsColorIgnored", 
"SettingsColorNormal", 
"SettingsColorReserved", 
"SettingsColors", 
"SettingsCommand", 
"SettingsCompressTransfers", 
"SettingsConfigureHubLists", 
"SettingsConfirmDialogOptions", 
"SettingsConfirmExit", 
"SettingsConfirmHubRemoval", 
"SettingsConfirmItemRemoval", 
"SettingsCzdc", 
"SettingsCzdcExtraDownloads", 
"SettingsDebugCommands", 
"SettingsDefaultAwayMsg", 
"SettingsDirect", 
"SettingsDirectories", 
"SettingsDisplayCheatsInMainChat", 
"SettingsDisplayDcUpdate", 
"SettingsDontDlAlreadyShared", 
"SettingsDownconn", 
"SettingsDownloadDirectory", 
"SettingsDownloadLimits", 
"SettingsDownloads", 
"SettingsDownloadsSubtitle", 
"SettingsDownloadsMax", 
"SettingsDownloadsSpeedPause", 
"SettingsExpandQueue", 
"SettingsExtensions", 
"SettingsExternalIp", 
"SettingsFakedetect", 
"SettingsFavShowJoins", 
"SettingsFavoriteDirs", 
"SettingsFavoriteDirsPage", 
"SettingsFileName", 
"SettingsFilesMax", 
"SettingsFilterMessages", 
"SettingsFilterEnter", 
"SettingsFirewallNat", 
"SettingsFirewallPassive", 
"SettingsFirewallUpnp", 
"SettingsFormat", 
"SettingsGeneral", 
"SettingsGetUserCountry", 
"SettingsHubUserCommands", 
"SettingsChange", 
"SettingsIgnoreHubPms", 
"SettingsIgnoreBotPms", 
"SettingsIncoming", 
"SettingsKeepLists", 
"SettingsLanguageFile", 
"SettingsLimit", 
"SettingsLogDir", 
"SettingsLogDownloads", 
"SettingsLogFilelistTransfers", 
"SettingsLogMainChat", 
"SettingsLogPrivateChat", 
"SettingsLogStatusMessages", 
"SettingsLogSystemMessages", 
"SettingsLogUploads", 
"SettingsLogWebserver", 
"SettingsLogging", 
"SettingsLogs", 
"SettingsMaxCompress", 
"SettingsMaxHashSpeed", 
"SettingsMaxTabRows", 
"SettingsMinimizeOnStartup", 
"SettingsMinimizeTray", 
"SettingsMouseOver", 
"SettingsName", 
"SettingsNetwork", 
"SettingsNoAwaymsgToBots", 
"SettingsNominalBandwidth", 
"SettingsNormal", 
"SettingsOdcShutdowntimeout", 
"SettingsOnlyHashed", 
"SettingsOpenNewWindow", 
"SettingsOperacolors", 
"SettingsOptions", 
"SettingsOutgoing", 
"SettingsOverride", 
"SettingsPersonalInformation", 
"SettingsPmBeep", 
"SettingsPmBeepOpen", 
"SettingsPmHistory", 
"SettingsPopunderFilelist", 
"SettingsPopunderPm", 
"SettingsPopupBotPms", 
"SettingsPopupHubPms", 
"SettingsPopupPms", 
"SettingsPorts", 
"SettingsPrioAutoprio", 
"SettingsPrioHigh", 
"SettingsPrioHighest", 
"SettingsPrioLow", 
"SettingsPrioLowest", 
"SettingsPrioNormal", 
"SettingsPromptPassword", 
"SettingsPublicHubList", 
"SettingsPublicHubListHttpProxy", 
"SettingsPublicHubListUrl", 
"SettingsQueue", 
"SettingsRenameFolder", 
"SettingsRequiresRestart", 
"SettingsReset", 
"SettingsRollback", 
"SettingsSbMaxSources", 
"SettingsSearchHistory", 
"SettingsSegment", 
"SettingsSelectColor", 
"SettingsSelectTextFace", 
"SettingsSelectWindowColor", 
"SettingsSendUnknownCommands", 
"SettingsShareHidden", 
"SettingsShareSize", 
"SettingsSharedDirectories", 
"SettingsShowInfoTips", 
"SettingsShowJoins", 
"SettingsShowProgressBars", 
"SettingsShowShellMenu", 
"SettingsSkipZeroByte", 
"SettingsSocks5", 
"SettingsSocks5Ip", 
"SettingsSocks5Port", 
"SettingsSocks5Resolve", 
"SettingsSocks5Username", 
"SettingsSortFavusersFirst", 
"SettingsSound", 
"SettingsSounds", 
"SettingsSpeedsNotAccurate", 
"SettingsStatusInChat", 
"SettingsTcpPort", 
"SettingsTlsPort", 
"SettingsTextStyles", 
"SettingsTimeStamps", 
"SettingsTimeStampsFormat", 
"SettingsToggleActiveWindow", 
"SettingsToolbar", 
"SettingsToolbarAdd", 
"SettingsToolbarImage", 
"SettingsToolbarRemove", 
"SettingsUdpPort", 
"SettingsUnfinishedDownloadDirectory", 
"SettingsUploadLineSpeed", 
"SettingsUploads", 
"SettingsUploadsSubtitle", 
"SettingsUploadsMinSpeed", 
"SettingsUploadsSlots", 
"SettingsUrlHandler", 
"SettingsUseCtrlForLineHistory", 
"SettingsUseExtensionDownto", 
"SettingsUseOldSharingUi", 
"SettingsUseSystemIcons", 
"SettingsUseTls", 
"SettingsUseVerticalView", 
"SettingsUserColors", 
"SettingsUserCommands", 
"SettingsUserMenu", 
"SettingsWebserver", 
"SettingsWindows", 
"SettingsWindowsOptions", 
"SettingsWriteBuffer", 
"SettingsZdcProgressOverride", 
"SettingsZdcProgressOverride2", 
"Shared", 
"SharedFiles", 
"ShowPopupAway", 
"ShowPopupMinimized", 
"ShowSpeed", 
"ShowLimit", 
"ShowSlots", 
"CustDesc", 
"Shutdown", 
"ShutdownAction", 
"ShutdownOff", 
"ShutdownOn", 
"Size", 
"SizeExact", 
"SizeMin", 
"SkipRename", 
"SlotGranted", 
"Slots", 
"SlotsSet", 
"SlowUser", 
"SmallFileSizeSet", 
"SocksAuthFailed", 
"SocksAuthUnsupported", 
"SocksFailed", 
"SocksNeedsAuth", 
"SocksSetupError", 
"SoundDownloadBegins", 
"SoundDownloadFinished", 
"SoundException", 
"SoundFakerFound", 
"SoundSourceAdded", 
"SoundTthInvalid", 
"SoundTypingNotify", 
"SoundUploadFinished", 
"SourceTooOld", 
"SourceType", 
"SpecifySearchString", 
"SpecifyServer", 
"Speed", 
"Status", 
"StoredPasswordSent", 
"StringNotFound", 
"Supports", 
"Suspend", 
"TabsOnTop", 
"Tag", 
"TargetFilenameTooLong", 
"Tb", 
"TcpPortBusy", 
"TextFakepercent", 
"TextManual", 
"Time", 
"TimeLeft", 
"TimestampHelp", 
"TimestampHelpDesc", 
"TimestampsDisabled", 
"TimestampsEnabled", 
"TooMuchData", 
"Total", 
"Transferlistdblclickaction", 
"Transferred", 
"TthAlreadyShared", 
"TthInconsistency", 
"TthRoot", 
"TwoColors", 
"Type", 
"UnableToCreateThread", 
"UnableToOpenFilelist", 
"UnableToRename", 
"UnableToSendFile", 
"UnignoreUser", 
"Unknown", 
"UnknownCommand", 
"UnknownError", 
"UpdateCheck", 
"UploadFinishedIdle", 
"UploadStarting", 
"UploadedBytes", 
"UploadedTo", 
"UpnpFailedToCreateMappings", 
"UpnpFailedToGetExternalIp", 
"UpnpFailedToRemoveMappings", 
"User", 
"UserCmdCommand", 
"UserCmdContext", 
"UserCmdFilelistMenu", 
"UserCmdHub", 
"UserCmdHubMenu", 
"UserCmdChat", 
"UserCmdOnce", 
"UserCmdParameters", 
"UserCmdPm", 
"UserCmdPreview", 
"UserCmdRaw", 
"UserCmdSearchMenu", 
"UserCmdTo", 
"UserCmdType", 
"UserCmdUserMenu", 
"UserCmdWindow", 
"UserDescription", 
"UserOffline", 
"UserOnline", 
"UserWentOffline", 
"UserWentOnline", 
"Userinfo", 
"UserlistIcons", 
"Userlistdblclickaction", 
"Userlistchatdblclickaction", 
"Users", 
"UsersOnline", 
"Version", 
"Video", 
"ViewAsText", 
"VirtualName", 
"VirtualNameExists", 
"VirtualNameLong", 
"Waiting", 
"WaitingFor", 
"WaitingForConnection", 
"WaitingTime", 
"WaitingToRetry", 
"WaitingUserOnline", 
"WaitingUsers", 
"WaitingUsersOnline", 
"Webserver", 
"WhatsThis", 
"WhoIs", 
"WinampHelp", 
"WinampHelpDesc", 
"Yes", 
"ZonealarmWarning", 
"SettingsStripTopic", 
"PasswordDesc", 
"PasswordTitle", 
"SettingsSkiplistShare", 
"CheckSettings", 
"WinampBack", 
"WinampPlay", 
"WinampPause", 
"WinampNext", 
"WinampStop", 
"WinampVolUp", 
"WinampVolHalf", 
"WinampVolDown", 
"ToggleToolbar", 
"WinampSpam", 
"Threshold", 
"PgPlugin", 
"GetIp", 
"UpdateIp", 
"PmPreview", 
"PrioFile", 
"PrioFileHighest", 
"PrioFileLowest", 
"PopupTime", 
"SettingsMisc", 
"SetSecondaryAway", 
"TicksSpeedDown", 
"TicksSpeedUp", 
"PsrDelay", 
"IpInChat", 
"CountryInChat", 
"Noon", 
"Midnight", 
"Am", 
"Pm", 
"HubSmall", 
"SettingsState", 
"EnableHubtopic", 
"Buffersize", 
"HideShare", 
"ShowJoins", 
"StealthMode", 
"AlreadyIgnored", 
"IgnoredUsers", 
"IgnoreClear", 
"FormatBiu", 
"ProtUsers", 
"ProtDesc", 
"WmpHelp", 
"WmpHelpDesc", 
"ItunesHelp", 
"ItunesHelpDesc", 
"MpcHelp", 
"MpcHelpDesc", 
"NoMediaSpam", 
"ProtFavs", 
"RawTexts", 
"SuperUser", 
"Opchat", 
"PgBlocked", 
"ExclChecks", 
"PopupBackColor", 
"PopupFont", 
"PopupTitleFont", 
"MaxMsgLength", 
"PopupImage", 
"ExceptionDialog", 
"ExceptionHeader", 
"ExceptionFooter", 
"ExceptionRestart", 
"ExceptionCopy", 
"ExceptionContinue", 
"ExceptionTerminate", 
"OpenLogsInternal", 
"NoEmotesLinks", 
"1", 
"IgnorePrivate", 
"UploadSpeedLimit", 
"SendToAllUsers", 
"BanSlots", 
"BanShare", 
"BanLimit", 
"BanMessage", 
"BanmsgPeriod", 
"BanStealth", 
"BanForcePm", 
"BanSkipOps", 
"ExtraslotToDl", 
"ClientId", 
"2", 
"GiveExtraSlot", 
"HighPriority", 
"NormalPriority", 
"LowPriority", 
"3", 
"DnsBare", 
"LocationBare", 
"4", 
"UserSummary", 
"UserWaitMenu", 
"NeedUserFilesMenu", 
"MagnetDlgSaveas", 
"BanColorDlg", 
"DupeColorDlg", 
"ModColorDlg", 
"PopupFavoriteDisconnected", 
"FavuserOffline", 
"MultilineChatInput", 
"ExternalPreview", 
"ExtraSlotTimeout", 
"ExtraSlotTimeFormat", 
"InvalidTimeFormat", 
"SlotGrantedMsg", 
"SlotRemovedMsg", 
"SendSlotgrantMsg", 
"AskSlot", 
"AskSlotTemplate", 
"Favuserlistdblclickaction", 
"5", 
"SettingsMessages", 
"SettingsProtectPrivate", 
"SettingsPassword", 
"SettingsPasswordHint", 
"DefPassword", 
"DefPasswordHint", 
"FreePmAccess", 
"CopyMlinkTempl", 
"SetFufile", 
"MenuFinishedDownloads", 
"MenuWaitingUsers", 
"MenuFinishedUploads", 
"UpTransferColors", 
"CmdFirstLine", 
"CmdAwayMsg", 
"CmdClearChat", 
"CmdFavJoins", 
"CmdShowJoins", 
"CmdTimeStamp", 
"CmdSlots", 
"CmdExtraSlots", 
"CmdSmallFiles", 
"CmdShareRefresh", 
"CmdShareRebuild", 
"CmdJoinHub", 
"CmdCloseWnd", 
"CmdFavHub", 
"CmdRmFav", 
"CmdUserlist", 
"CmdIgnorelist", 
"CmdFavUser", 
"CmdSendPm", 
"CmdGetlist", 
"CmdConnection", 
"CmdFlylinkdc", 
"CmdStats", 
"CmdUrl", 
"CmdSaveQueue", 
"CmdDoSearch", 
"CmdShutdown", 
"CmdMe", 
"CmdWinamp", 
"CmdHelpInfo", 
"PassiveNotice", 
"StartupBackup", 
"AdlBrief", 
"AdlTitle", 
"TitleIpfilter", 
"ErrIpfilter", 
"IpfilterPathWay", 
"IpfilterCurRules", 
"IpfilterConfiguredDependingOnProvider", 
"IpfilterGroupbox", 
"GlobalHubframeConf", 
"Comment", 
"Regexp", 
"CaseSensitive", 
"InvalidRegexp", 
"RegexpTester", 
"RegexpMatch", 
"RegexpMismatch", 
"CaseInsensitiveRegexp", 
"Match", 
"NoAdls", 
"Global", 
"Action", 
"NoAction", 
"ForbiddenFiles", 
"OpchatInstr", 
"ProfileVersion", 
"ProfileNfo", 
"SettingsParams", 
"NameRegexpEmpty", 
"UseAntivir", 
"UseRegexpOrWc", 
"StealthyIndicateSpeeds", 
"OldTrayBehav", 
"OldNamingStyle", 
"SettingsDupeColor", 
"NoTthCheat", 
"DisconnectRaw", 
"TimeoutRaw", 
"FakeshareRaw", 
"ListlenMismatch", 
"FilelistTooSmall", 
"FilelistUnavailable", 
"OldClientRaw", 
"SetAction", 
"DeleteChecked", 
"ClientCheckingFinishedIdle", 
"MenuTopmost", 
"LockToolbars", 
"AutoCompleteSearch", 
"KeepDlHistory", 
"KeepUlHistory", 
"FakeSet", 
"RawSet", 
"LogChat", 
"FavProtUsers", 
"UnusedToggleQsearch", 
"QsearchStr", 
"SearchDetectTth", 
"FullFilelistNfo", 
"NoDownloadsFromBot", 
"IconsMode", 
"ZionMode", 
"SdcMode", 
"ZionTabs", 
"NonHubsFront", 
"GlobalMiniTabs", 
"MiniTab", 
"NormalTab", 
"OldPw", 
"NewPw", 
"ConfirmNewPw", 
"BlendOfflineSearch", 
"MaxResizeLines", 
"Incoming", 
"Outgoing", 
"Begin", 
"End", 
"AutoOpenOpChat", 
"CzdcRatiomsg", 
"RatioMsgHelp", 
"RatioMsgHelpDesc", 
"WinampNotRunning", 
"MenuJoinTeam", 
"MenuHlp", 
"UseCustomListBackground", 
"BufferStr2", 
"TransferViewTitle", 
"TransferViewButtonHide", 
"TransferViewButtonShow", 
"UserListTitle", 
"UserListFilterCaption", 
"SearchTypeTth", 
"SearchTypeCdImage", 
"SearchSizeDontCare", 
"PeersToolbarSearchPrompt", 
"PeersToolbarSearchButton", 
"PeersToolbarExpand", 
"PeersToolbarCollapse", 
"PeersToolbarDownloadQueue", 
"PeersToolbarUploadQueue", 
"UserListNick", 
"UserListContacts", 
"PeersToolbarChat", 
"QueueSaved", 
"HubChatFrameTitle", 
"PrivateChatFrameTitle", 
"FilelistTitle", 
"FilelistDownloadFile", 
"FilelistDownloadDir", 
"FilelistFilemenuDownloadDir", 
"FilelistFilemenuDownloadDirTo", 
"FilelistFilemenuVideo", 
"SettingsCheckboxExpertMode", 
"SettingsNetworkHelpLink", 
"SettingsUploadHelpLink", 
"SettingsGeneralValidationNickEmpty", 
"SettingsSearch", 
"SettingsSearchExpandToolbarOnActivate", 
"SearchRestoreConditionOnActivate", 
"MenuEnableSounds", 
"MenuOptionsSettings", 
"MenuAway", 
"TransferViewColumnUser", 
"TransferViewColumnStatus", 
"HintDownloadQueue", 
"HintUploadQueue", 
"HintFinishedDownloads", 
"HintFinishedUploads", 
"DownloadQueueTitle", 
"DownloadPauseHint", 
"DownloadStartHint", 
"DownloadDeleteHint", 
"DownloadPriorityLabel", 
"DirectoryListingAddToFavoritesHint", 
"DirectoryListingPrivateMessageHint", 
"HubInfoReconnectHint", 
"HubInfoConfigureHint", 
"HubInfoAddFilesHint", 
"HubInfoOpenFileListHint", 
"HubInfoRefreshFileListHint", 
"SettingsProviderTitle", 
"SettingsProviderNotice", 
"SettingsGeneralProviderNotSelected", 
"SettingsMagnetpage", 
"SettingsMagnetAskInDialog", 
"SettingsMagnetActionLabel", 
"SettingsMagnetActionDownload", 
"SettingsMagnetActionSearch", 
"MenuAdviceWindow", 
"MenuSubscriptionWindow", 
"MenuSubscriptions", 
"BlockedByIpfilter", 
"OpenHubChatOnConnect", 
"MinimizeOnClose", 
"CustomVideoPlayer", 
};
